# Generated by Django 3.0.3 on 2020-09-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0003_auto_20200918_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
